version : '3.9'

# services generally mean container, services are terms for kubernetes
services:
  go-app:
    container_name: go-app # useful for communications btwn diff TYPES of container
    build: . # this will use the Dockerfile in current directory to create image and run it as a container
    environment:
      DATABASE_URL: "host=go_db username=postgres password=postgres dbname=postgres sslmode=disable" # DATABASE_URL must be same as env variable set in main, sslmode is for security = true in prod
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}